### ISSUE TITLE
Facebook Login által visszaadott json: null

### ISSUE THREAD

**Issue by kardosorsi** [tyaty1/coffeguest_backend#8]

**Comment by tyaty1** [comment]
Próbálj meg újra regisztrálni.

**Comment by tyaty1** [comment]
Most mit ír ki?

**Comment by kardosorsi** [comment]
még mindig null, regisztrálok facebookra egy másik usert és felveszem tesztelőnek a facebook apinál az apphoz

**Comment by tyaty1** [comment]
Most jelenleg ki kéne írnia, hogy pontosan mit szedett ki a token-ből(ha elfogadta)

**Comment by tyaty1** [comment]
Facebook tökéletesen működik most én API-mmal.
